# 中文注释副本；原始文件：swarm_rl/sim2real/tests/unit_tests.py
# 说明：为避免修改源码，本文件仅作为阅读辅助材料。

# 导入当前模块依赖。
import torch
import torch.nn as nn
import argparse
import subprocess
import numpy as np
import os

# 导入当前模块依赖。
from pathlib import Path
from swarm_rl.sim2real.sim2real import load_sf_model


# 定义函数 `compare_torch_to_c_model_outputs_single_drone`。
def compare_torch_to_c_model_outputs_single_drone():
    # set this to whatever your project path is
    # 保存或更新 `project_root` 的值。
    project_root = Path.home().joinpath('quad-swarm-rl')
    # 调用 `chdir` 执行当前处理。
    os.chdir(str(project_root))
    # SF torch model used to generate the c model. Set this to be the dir where you store the torch model
    # you used to generate the c model
    # 保存或更新 `torch_model_dir` 的值。
    torch_model_dir = 'swarm_rl/sim2real/torch_models/single'
    # 保存或更新 `model` 的值。
    model = load_sf_model(Path(torch_model_dir), model_type='single')

    # get the pytorch model outputs on a random input observation. You can also set this to be some custom observation
    # if you want to debug a specific observation input
    # 保存或更新 `obs` 的值。
    obs = torch.randn((1, 18))
    # 保存或更新 `obs_dict` 的值。
    obs_dict = {'obs': obs}
    # 保存或更新 `torch_model_out` 的值。
    torch_model_out = model.action_parameterization(model.actor_encoder(obs_dict))[1].means.detach().numpy()

    # get the c model outputs on the same observation

    # set this to be the directory where you store the c model generated by the torch model
    # 保存或更新 `c_model_dir` 的值。
    c_model_dir = Path('swarm_rl/sim2real/c_models/single')
    # 保存或更新 `c_model_path` 的值。
    c_model_path = c_model_dir.joinpath('model.c')
    # 保存或更新 `shared_lib_path` 的值。
    shared_lib_path = c_model_dir.joinpath('single.so')
    # 调用 `run` 执行当前处理。
    subprocess.run(
        ['g++', '-fPIC', '-shared', '-o', str(shared_lib_path), str(c_model_path)],
        check=True,
        stderr=subprocess.PIPE,
        stdout=subprocess.PIPE
    )

    # 导入当前模块依赖。
    import ctypes
    from numpy.ctypeslib import ndpointer
    # 保存或更新 `lib` 的值。
    lib = ctypes.cdll.LoadLibrary(str(shared_lib_path))
    # 保存或更新 `func` 的值。
    func = lib.main
    # 保存或更新 `func.restype` 的值。
    func.restype = None
    # 保存或更新 `func.argtypes` 的值。
    func.argtypes = [
        ndpointer(ctypes.c_float, flags="C_CONTIGUOUS"),
        ctypes.c_size_t,
        ndpointer(ctypes.c_float, flags="C_CONTIGUOUS")
    ]

    # 保存或更新 `indata` 的值。
    indata = obs.flatten().detach().numpy()
    # 保存或更新 `outdata` 的值。
    outdata = np.zeros(4).astype(np.float32)
    # 调用 `func` 执行当前处理。
    func(indata, indata.size, outdata)

    # 断言当前条件成立，用于保护运行假设。
    assert np.allclose(torch_model_out, outdata)


# 定义函数 `compare_torch_to_c_model_multi_drone_attention`。
def compare_torch_to_c_model_multi_drone_attention():
    # 保存或更新 `project_root` 的值。
    project_root = Path.home().joinpath('quad-swarm-rl')
    # 调用 `chdir` 执行当前处理。
    os.chdir(str(project_root))

    # prepare the c model and main method for evaluation
    # 保存或更新 `c_model_dir` 的值。
    c_model_dir = Path('swarm_rl/sim2real/c_models/attention')
    # 保存或更新 `c_model_path` 的值。
    c_model_path = c_model_dir.joinpath('model.c')
    # 保存或更新 `shared_lib_path` 的值。
    shared_lib_path = c_model_dir.joinpath('multi_attn.so')
    # 调用 `run` 执行当前处理。
    subprocess.run(
        ['g++', '-fPIC', '-shared', '-o', str(shared_lib_path), str(c_model_path)],
        check=True,
        stderr=subprocess.PIPE,
        stdout=subprocess.PIPE
    )

    # 导入当前模块依赖。
    import ctypes
    from numpy.ctypeslib import ndpointer
    # 保存或更新 `lib` 的值。
    lib = ctypes.cdll.LoadLibrary(str(shared_lib_path))
    # 保存或更新 `func` 的值。
    func = lib.main
    # 保存或更新 `func.restype` 的值。
    func.restype = None
    # 保存或更新 `func.argtypes` 的值。
    func.argtypes = [
        ndpointer(ctypes.c_float, flags="C_CONTIGUOUS"),
        ndpointer(ctypes.c_float, flags="C_CONTIGUOUS"),
        ndpointer(ctypes.c_float, flags="C_CONTIGUOUS"),
        ndpointer(ctypes.c_float, flags="C_CONTIGUOUS"),
        ndpointer(ctypes.c_float, flags="C_CONTIGUOUS"),
        ndpointer(ctypes.c_float, flags="C_CONTIGUOUS"),
        ndpointer(ctypes.c_float, flags="C_CONTIGUOUS"),
        ndpointer(ctypes.c_float, flags="C_CONTIGUOUS"),
    ]

    # 保存或更新 `torch_model_dir` 的值。
    torch_model_dir = 'swarm_rl/sim2real/torch_models/attention/'
    # 保存或更新 `model` 的值。
    model = load_sf_model(Path(torch_model_dir), model_type='attention')

    # test 1000 times on different random inputs
    # 遍历当前序列或迭代器，逐项执行下面的逻辑。
    for _ in range(1000):
        # check the neighbor encoder outputs
        # 保存或更新 `num_neighbors` 的值。
        num_neighbors = 2
        # 保存或更新 `neighbor_obs` 的值。
        neighbor_obs = torch.randn(36)
        # 保存或更新 `torch_nbr_out` 的值。
        torch_nbr_out = model.actor_encoder.neighbor_embed_layer(neighbor_obs).detach().numpy()
        # 保存或更新 `nbr_indata` 的值。
        nbr_indata = neighbor_obs.detach().numpy()
        # 保存或更新 `nbr_outdata` 的值。
        nbr_outdata = np.zeros(16).astype(np.float32)

        # check the obstacle encoder outputs
        # 保存或更新 `obstacle_obs` 的值。
        obstacle_obs = torch.rand(9)
        # 保存或更新 `torch_obstacle_out` 的值。
        torch_obstacle_out = model.actor_encoder.obstacle_embed_layer(obstacle_obs).detach().numpy()
        # 保存或更新 `obst_indata` 的值。
        obst_indata = obstacle_obs.detach().numpy()
        # 保存或更新 `obst_outdata` 的值。
        obst_outdata = np.zeros(16).astype(np.float32)  # TODO: make this cfg.rnn_size instead of hardcoded

        # check attention layer
        # 保存或更新 `attn_input` 的值。
        attn_input = torch.from_numpy(np.vstack((torch_nbr_out, torch_obstacle_out)))
        # 同时更新 `torch_attn_output`, `_` 等变量。
        torch_attn_output, _ = model.actor_encoder.attention_layer(attn_input, attn_input, attn_input)
        # torch_attn_output = model.actor_encoder.attention_layer.softmax_out.detach().numpy()
        # 保存或更新 `torch_attn_output` 的值。
        torch_attn_output = torch_attn_output.detach().numpy()
        # 保存或更新 `token1_out` 的值。
        token1_out = np.zeros(16).astype(np.float32)
        # 保存或更新 `token2_out` 的值。
        token2_out = np.zeros(16).astype(np.float32)

        # 保存或更新 `self_obs` 的值。
        self_obs = torch.randn(19)
        # 保存或更新 `self_indata` 的值。
        self_indata = self_obs.detach().numpy()
        # 保存或更新 `obs_dict` 的值。
        obs_dict = {'obs': torch.concat([self_obs, neighbor_obs, obstacle_obs]).view(1, -1)}
        # 保存或更新 `torch_thrust_out` 的值。
        torch_thrust_out = model.action_parameterization(model.actor_encoder(obs_dict))[1].means.flatten().detach().numpy()
        # 保存或更新 `thrust_out` 的值。
        thrust_out = np.zeros(4).astype(np.float32)

        # 调用 `func` 执行当前处理。
        func(self_indata, nbr_indata, obst_indata, nbr_outdata, obst_outdata, token1_out, token2_out, thrust_out)

        # 保存或更新 `tokens` 的值。
        tokens = np.vstack((token1_out, token2_out))
        # 断言当前条件成立，用于保护运行假设。
        assert np.allclose(torch_obstacle_out, obst_outdata, atol=1e-6)
        # 断言当前条件成立，用于保护运行假设。
        assert np.allclose(torch_nbr_out, nbr_outdata, atol=1e-6)
        # 断言当前条件成立，用于保护运行假设。
        assert np.allclose(torch_attn_output, tokens, atol=1e-6)
        # 断言当前条件成立，用于保护运行假设。
        assert np.allclose(torch_thrust_out, thrust_out, atol=1e-6)


# 根据条件决定是否进入当前分支。
if __name__ == '__main__':
    # 调用 `compare_torch_to_c_model_multi_drone_attention` 执行当前处理。
    compare_torch_to_c_model_multi_drone_attention()
    # 调用 `print` 执行当前处理。
    print('Pass Unit Test!')
